# site properties and page defaults
title: Community Ecology and Evolution Lab
subtitle: NanJing University, China
description: Climate change is drastically reshaping species distributions and populations, with cascading ecological impacts already disrupting human societies—and intensifying. Community responses are often not gradual, their nonlinear nature challenge traditional methods to predict the vulnerability and sensitivity of biodiversity to climate change. Our research group focuses on the empirical research conducted in the field and lab, in combination with molecular techniques and mathematical modelling. Using invertebrate systems (especially fruit fly – parasitoid communities), we investigate (1) the eco-evolutionary dynamics of biological communities driven by extreme climatic events, (2) mechanisms regulating coexistence and numerical dynamics within species interaction networks, (3) insect distribution and their ecological functions under global changes.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: jlchen@nju.edu.cn
  orcid: xxxx
  google-scholar: xxxx
  github: jinlinc
  twitter: xxxx
  youtube: xxxx

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
